### ISSUE TITLE
run example app failed, AndroidX

### ISSUE THREAD

**Issue by kmfish** [flutter-thrio/thrio#26] opened 2020-05-06 10:49 UTC
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the
    steps on https://goo.gl/CP92wY.
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:checkDebugDuplicateClasses'.            
> 1 exception was raised by workers:                                    
  java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
  Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
  Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
  Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)

**Comment by foxsofter** [comment] 2020-05-06 12:00
> [!] Your app isn't using AndroidX.
> To avoid potential build failures, you can quickly migrate your app by following the
> steps on https://goo.gl/CP92wY.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> > 1 exception was raised by workers:
> > java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
> > Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
> > Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)
> > Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (androidx.core:core:1.1.0) and classes.jar (com.android.support:support-compat:28.0.0)

Duplicate of #23

**Closed as completed** 2020-05-07 09:26 UTC
Labels: duplicate
